services:
  db:
    image: postgres:latest
    container_name: academy-postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tododb
    ports:
      - 5433:5432
    volumes:
      - ./db:/var/lib/postgresql/data"